initial setup
CDCgov/covid-vaccine-uptake-2023 pull request #1
Opened 2024-11-15 22:01 UTC by iholmdahl

This contains all scripts and functions that should be necessary to recreate the analysis and figures in the manuscript!

2024-11-18 20:55 UTC, swo requested changes
- Missing a README, which should have the boilerplate/disclaimers as well as a "Getting Started" section
- This project is not renv enabled, which means that it might be more difficult to write the "getting started" bit. I'll try to get started on my own and see what roadblocks I hit.
- Some small suggested tweaks to the code

2024-11-18 20:55 UTC, swo commented on uptakeprojection/R/get_nis_2022.R
> +      group_category = case_when(
Should use `case_match()` here

2024-11-18 20:55 UTC, swo commented on uptakeprojection/R/get_nis_2022.R
> +      group_name = ifelse(group_name == "Race/Ethnicity (7 level)", "Race/Ethnicity", group_name),
this seems like another series of places where `case_match()` would clarify what's going on

2024-11-18 22:00 UTC, swo commented
See #2 for my suggestion about how to get the R package into compliance

I tried to `devtools::load_all("uptakeprojection"); source("scripts/setup.R"); source("scripts/fit_slopes.R"); source("scripts/project_uptake.R")`, but I get an error `object 'max_date' not found`, which I think is because of `fit_slopes.R` line 10

2024-11-19 17:24 UTC, iholmdahl commented
> I tried to `devtools::load_all("uptakeprojection"); source("scripts/setup.R"); source("scripts/fit_slopes.R"); source("scripts/project_uptake.R")`, but I get an error `object 'max_date' not found`, which I think is because of `fit_slopes.R` line 10

I don't know how the README got deleted but I've added it back in! It clarifies that you only need to run setup.R and then project_uptake.R.

2024-11-21 23:52 UTC, swo commented
> I tried to `devtools::load_all("uptakeprojection"); source("scripts/setup.R"); source("scripts/fit_slopes.R"); source("scripts/project_uptake.R")`, but I get an error `object 'max_date' not found`, which I think is because of `fit_slopes.R` line 10

It looks like `max_date` gets defined in `project_uptake.R`, so that would need to be sourced before `fit_slopes.R`. Is there a way around that?

2024-11-22 13:27 UTC, iholmdahl commented
> > I tried to `devtools::load_all("uptakeprojection"); source("scripts/setup.R"); source("scripts/fit_slopes.R"); source("scripts/project_uptake.R")`, but I get an error `object 'max_date' not found`, which I think is because of `fit_slopes.R` line 10
> 
> It looks like `max_date` gets defined in `project_uptake.R`, so that would need to be sourced before `fit_slopes.R`. Is there a way around that?

You should not need to run `fit_slopes.R` -- it's sourced by `project_uptake.R`

2024-11-22 20:24 UTC, swo approved these changes

2024-11-22 21:09 UTC, merged