CI: run R CHECK
CDCgov/covid-vaccine-uptake-2023 pull request #2
Opened 2024-11-18 20:51 UTC by swo

2024-11-19 17:20 UTC, iholmdahl requested changes
Overall I think this is fine (thanks for the help with package compliance!). I can't tell which change exactly it is but something in the update to stan_slope.R is causing it to fail when I run the script.

2024-11-19 17:20 UTC, iholmdahl commented on uptakeprojection/R/stan_slope.R
This file is no longer running for me, causing project_uptake.R (which depends on fit_slopes.R) to fail.

2024-11-21 23:42 UTC, swo commented on uptakeprojection/R/stan_slope.R
What kind of error message do you get?

2024-11-21 23:52 UTC, swo commented on uptakeprojection/R/stan_slope.R
Is this the same as: https://github.com/CDCgov/covid-vaccine-uptake-2023/pull/1#issuecomment-2492587358 ?

2024-11-22 13:34 UTC, iholmdahl commented on uptakeprojection/R/stan_slope.R
the message is:

`Error in `mutate()`:
ℹ In argument: `stan = purrr::map(fit_data, stan_slope_summary)`.
Caused by error in `purrr::map()`:
ℹ In index: 1.
Caused by error in `h()`:
! error in evaluating the argument 'object' in selecting a method for function 'extract': 'data' must be a list, environment, or character vector`

when i'm running `project_uptake.R` -- it comes in when `fit_slopes.R` gets to running the `stan_slope.R` function

2024-11-22 15:06 UTC, swo commented on uptakeprojection/R/stan_slope.R
This was a problem of `c()` vs. `list()`

2024-11-22 17:53 UTC, iholmdahl requested changes
This is working now -- will be fine once it's passing checks

2024-11-22 20:18 UTC, iholmdahl approved these changes

2024-11-22 20:18 UTC, merged